### ISSUE TITLE
Admin PM

### ISSUE THREAD

**Issue by Signmark** [ITBlackwood/ATMTA-Paradise#105]
**Описание проблемы**:
Admin PM не работает.

**Что должно было произойти**: 
В чате должно высветиться сообщение при отправке Admin PM

**Что произошло вместо этого**:
Приходит только звуковое оповещение

**Почему это плохо/Какие последствия этого:**
Ахелп сломан! Сообщения в ахелп приходят, однако ответить на них через Admin PM невозможно

**Детальное описание как повторить возникновение проблемы**:
1. Иметь доступ к админке.
2. Написать себе же в ахелп
3. Попытаться ответить

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Надо еще глянуть как на оригинальном парадайзе там, может и у них такая проблема, а может это обосрамс наш, с санитайзами и прочим

**Comment by ITBlackwood** [comment]
Я же уже говорил - есть где-то в коде модуля ОДНА ебучая строчка которая жрет все не-латинские символы.

**Comment by Signmark** [comment]
REKT
