### ISSUE TITLE
ВЖИКВЖИКВЖИК Инстагиб алиумов.

### ISSUE THREAD

**Issue by ITBlackwood** [ITBlackwood/ATMTA-Paradise#126]
**Описание проблемы**:
При поглощении алиумом человека, у которого есть режущий предмет в руках, человек может начать спамить резист, который гибнет алиума за секунду.

**Что должно было произойти**: 
Должен наноситься урон, но при этом должен быть КД.

**Что произошло вместо этого**:
Буквально за мгновение распидорасило. 

**Почему это плохо/Какие последствия этого:**
Это странно?

**Детальное описание как повторить возникновение проблемы**:
Сожрать человека с ножом (например). Человек жмакает атаку/резист, и при этом наносит по 25 урона алиуму изнутри. Без кулдауна, можно просто резко нажать четыре раза и инстагибнуть ксеноморфа, при этом самому остаться невредимым.
**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 

ЭТА ХУЙНЯ РАБОТАЕТ ДАЖЕ ЕСЛИ АЛИУМ ЗАЛЕЗ В ТРУБУ.

**Comment by Signmark** [comment]
алиумы же сломанные, а это я называю КОНТРПОЛОМКА

**Comment by ITBlackwood** [comment]
Протестили отдельно в админ руме - почему-то работало исправно, а в трубах алиума дамажить было нельзя. Как? Почему? А хуй его знает. Баг закрываю.
