### ISSUE TITLE
Nanoui cyrrilic letters crash

### ISSUE THREAD

**Issue by Injazz** [ITBlackwood/ATMTA-Paradise#16]
**Problem Description**:
NanoUI console crashes when you trying to input some cyrillic symbols (Supply Shuttle Console for example, or PDA)

**What did you expect to happen**: 
Normal NanoUI console output

**What happened instead**:
Blank console without interface

**Why is this bad/What are the consequences:**
You can't write anything in cyrillic without a NanoUI crash

**Steps to reproduce the problem**:
Open PDA messenger and write letter in cyrillic. Open Supply Shuttle Console and write reason for call in cyrillic.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Looks like it related to new 510 runtime json encoder or whatever they calls that shit.

**Comment by ITBlackwood** [comment]
Что если заменить sanitize_local на обычный санитайз?

**Comment by Injazz** [comment]
@ITBlackwood Надеюсь это поможет
