### ISSUE TITLE
Emergency Shuttle Bug

### ISSUE THREAD

**Issue by Injazz** [ITBlackwood/ATMTA-Paradise#17]
**Problem Description**:
You can't call Emergency shuttle from console. You can ask AI or admin to call it though

**What did you expect to happen**: 
Shuttle coming to station within the ETA

**What happened instead**:
NO SHUTTLE

**Why is this bad/What are the consequences:**
Yeah it's kinda bad, because you can't save yourself with traitor AI and also without admins who can call shuttle

**Steps to reproduce the problem**:
Come to Communication Console and call shuttle...but nobody came

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: LOOKS LIKE WE FUCKED UP EVERYTHING

**Comment by Zurro13** [comment]
Если я правильно понял, то с консоли шаттл вызывается через shuttle_master.requestEvac в /proc/call_shuttle_proc(var/mob/user, var/reason), а трансфер через shuttle_master.emergency.request в /proc/init_shift_change или в /client/proc/admin_call_shuttle() у админов. Видимо проблема в этом.

**Comment by ITBlackwood** [comment]
Нет, проблема не в этом, насколько мы знаем. Эти же процессы не изменены по стандарту.

**Comment by Injazz** [comment]
@ITBlackwood изменены.
