### ISSUE TITLE
Может быть, другую сборочку взять?

### ISSUE THREAD

**Issue by vlandemart** [ITBlackwood/ATMTA-Paradise#18]
Парадайз сборка фул оф багс и недоработок
Их медицина не нормально работает с расами. Например, дионы подсаживаются на морфин(!). Еще из багов - картины работают через жёппу, только создатель их видит, у остальных они невидимые
Мусорный мешок может привариться к руке, и ты его никак не снимешь, мне приходилось ампутировать руку.
Еще и проблемы с кириллицей у вас пошли - консоли и ПДА вылетают из-за них(хотя они и до обновления бьенда до 5.10 вылетали и ломались через 30-60 минут игры)

**Comment by Injazz** [comment]
Мы прошли точку невозврата и смена билда - просто потеря времени (а еще отразится на производительности)

**Comment by ITBlackwood** [comment]
МАМА, МАМА, Я НЕ РАЗБИРАЮСЬ В БИЛДАХ И БАГАХ НО СЧИТАЮ СВОИМ ДОЛГОМ ПРЕДЛОЖИТЬ ХУЙНЮ КОТОРУЮ ОТВЕРГАЛИ УЖЕ ОВЕРДОХУЯ РАЗ.

"КОНЕЕЕЕЕЧНО ЭТО ЖЕ ПАРАДАЙЗОВСКИЙ БИЛД БАГОВАН, ЛЮБОЙ ДРУГОЙ ТОЧНО БУДЕТ НОРМАЛЬНЫМ, Я УВЕРЕН"

КОНЕЕЕЕЧНО ВИНОВАТ БИЛД А НЕ БЕТА ВЕРСИЯ БЬОНДА С ЕГО ХУЕВЫМ ВЗАИМОДЕЙСТВИЕМ С КИРИЛЛИЦЕЙ

Фак ю. 
Просто. 
Уходи. Не возвращайся.
