### ISSUE TITLE
Copy to paper from buffer cirrilic swap to ???? 

### ISSUE THREAD

**Issue by Utrit** [ITBlackwood/ATMTA-Paradise#20]
**Problem Description**:
При копирование русского текста на бумажку происходит превращение в кучу ?????

**What did you expect to happen**: 
Бюрократия сломана из-за всего этого

**What happened instead**:
Бумажка полная транслита или вопросиков не круто

**Why is this bad/What are the consequences:**
Бюрократия сломана из-за всего этого

**Steps to reproduce the problem**:
Во всем виновата кирилица

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Всегда :(

**Comment by Injazz** [comment]
good english m9 i r7 dis 10/10
Тут можно писать на русском

**Comment by Injazz** [comment]
Обновил шаблон

**Comment by Injazz** [comment]
@Utrit на русском объясни, как воспроизвести баг

**Comment by ITBlackwood** [comment]
Короче эта проблема легко фиксится изменением кодировки. Как менять кодировку? Пропускаешь весь текст через Wordpad,  оттуда же снова копируешь и вставляешь в лист на игре.
