### ISSUE TITLE
Сломаные костюмчики.

### ISSUE THREAD

**Issue by ITBlackwood** [ITBlackwood/ATMTA-Paradise#30]
**Описание проблемы**:
Иконки многих костюмов (suit) не отображаются)

**Что должно было произойти**: 
Должны отображаться, очевидно

**Что произошло вместо этого**:
Отсутствует иконка на персонаже.

**Почему это плохо/Какие последствия этого:**
Потому что костюмы - важная часть геймплея.

**Детальное описание как повторить возникновение проблемы**:
Одень любой suit. Халат, например, лабораторный.

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Лишних подробностей кроме той, что виноват думгай нет.

**Comment by Injazz** [comment]
SUIT?

**Comment by Injazz** [comment]
ЧЕГООООООООООООООООООООООООООООО
