### ISSUE TITLE
FLAGI ZATOPEELO

### ISSUE THREAD

**Issue by ColonelGovno** [ITBlackwood/ATMTA-Paradise#32]
**Описание проблемы**:
За ответы на факсы отвечает флаг +EVENT, а не +ADMIN. В следствии чего, у большенства активных админов нет доступа к факсу.

**Что должно было произойти**: 
В идеале в чатике появляется сообщение, где есть кнопка "Прочитать" и "Ответить".

**Что произошло вместо этого**:
Абсолютно ничего.

**Почему это плохо/Какие последствия этого:**
ДА ЭТО ОЧЕНЬ ВАЖНО КАК ЕЩЕ ВЫЗВАТЬ ДУМСКВАД ИНГЕЙМ?

**Детальное описание как повторить возникновение проблемы**:
1. Идешь к факсу, авторизируешься.
2. Пишешь сообщение и отсылаешь на источник "Central Command".
3. Ничего не получаешь в ответ, так как флагов нема.

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Ну у меня была ОПка.

**Comment by ITBlackwood** [comment]
Флаги выданы.
