### ISSUE TITLE
МАМ ПАКМАН И ВЕНДОМАТ СЛОМАНЫ.

### ISSUE THREAD

**Issue by Templariumer** [ITBlackwood/ATMTA-Paradise#34]
**Описание проблемы**:
ПАКМАН и вендомат не работают.

**Что должно было произойти**: 
Должна была происходить зарядка СМЕСа

А в вендоматах сломан переход между страницами
**Что произошло вместо этого**:
Нажимая на START, вокруг кнопки крутится кружок и происходить ЁБАНОЕ НИЧЕГО

А в вендоматах крутится кружок и переход не происходит, пока не закроешь окно и не откроешь заного

**Почему это плохо/Какие последствия этого:**
Когда в СМЕСах по 0%, приятней пакман подрубить и быстренько всё включить, а не настраивать соляры.

И напрягает закрывать\открывать.
**Детальное описание как повторить возникновение проблемы**:

1. Настраиваешь ПАКМАН(НА ВИКИ ИДИ Я ТУТ ГУИД ПИСАТЬ НЕ БУДУ)
2. Нажимаешь START.
3. Пишешь в Ахелп и пиздуешь на гитхаб

1. Открываешь вендомат
2. Нажимаешь на любую кнопку с едой\водой\сигами

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Я подозреваю,(Я НЕ РАЗБИРАЮСЬ В КОДЕ) что это как-то связано с красивым UI.
Яцун где пуп?

**Comment by ITBlackwood** [comment]
> **_Яцун где пуп?_**

Ах ты мерзавец
