### ISSUE TITLE
Блоб слишком ОП

### ISSUE THREAD

**Issue by ITBlackwood** [ITBlackwood/ATMTA-Paradise#36]
**Описание проблемы**:
МАМ ОНО НЕ КОНТРИЦА

**Что должно было произойти**: 
А ДОЛЖНО КОНТРИЦА

**Что произошло вместо этого**:
ОНО НАС СКУШАЛО

**Почему это плохо/Какие последствия этого:**
ТАКОЙ РАУНД ХОРОШИЙ ИСПОРТИЛИ

**Детальное описание как повторить возникновение проблемы**:
СПАВНИ БЛОБА И КУШАЙ ВСЕ

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Экста, блоб выпал рандомно

**Comment by Injazz** [comment]
Предлагаю повысить минимальное количество игроков до 30 и тогда все решится

если уж приспичит то блоб вызывается через дебаг

**Comment by ITBlackwood** [comment]
Что ж, это будет вполне acceptable
