### ISSUE TITLE
Перевести все, что говорит игрок, на РУССКИЙ

### ISSUE THREAD

**Issue by Injazz** [ITBlackwood/ATMTA-Paradise#37]
Как вы знаете, при включений определенных генов или из-за болезни и еще чего-нибудь, игрок может выкрикивать разные реплики. Но они все на английском! Соответственно их крайне легко заметить, что убивает часть геймплейных фич, заложенные в эти гены/болезни.

Призываю людей нам на помощь. Будем все это переводить!
Ищите, где подобная генерация чат-сообщений происходит в коде, и либо сообщайте нам прямо в это треде, либо исправляйте сами и делайте пулл-реквесты с пометкой [ПЕРЕВОД].

**Comment by NazarFogmann** [comment]
Нам самим искать? или вы дадите линк на файлик?

**Comment by Zurro13** [comment]
Я так понимаю, это файлики в \code\modules\flufftext\

**Comment by Feno4ka** [comment]
[https://github.com/ITBlackwood/ATMTA-Paradise/blob/master/code/modules/mob/living/carbon/human/life.dm#L103](url) Прошу

**Comment by Zurro13** [comment]
Почти там же, но в /code/modules/mob/living/carbon/human/say.dm
в /mob/living/carbon/human/handle_speech_problems еще немного есть

**Comment by Injazz** [comment]
Не трогайте эмоуты, @Zurro13, @NazarFogmann

**Comment by Injazz** [comment]
кароч это пока отложим до тех пор, пока не завезут нормальный модуль для локализации, так как в коде кириллица не воспринимается совсем
