### ISSUE TITLE
[не проверялось]Код вызова шаттла, возможные ошибки с точки зрения логики. 

### ISSUE THREAD

**Issue by Zurro13** [ITBlackwood/ATMTA-Paradise#39]
**Описание проблемы**:

Отличия в /proc/call_shuttle_proc и /proc/init_shift_change

if(ticker.mode.name == "blob") в первом случае и if(ticker.mode.name == "epidemic") во втором.

**Что должно происходить**: 
По логике шаттл не должен вызываться, если на станции блоб.

**Что произошло вместо этого**:
Я так подозреваю, что эвакуационный шаттл не придет (или по крайней мере не должен), но шаттл трансфера будет вызван при успешном голосовании.

**Почему это плохо/Какие последствия этого:**
При отсутствии блоба не важна вообще, при наличии блоба возможность прилета трансфера при невозможности вызова эвакуационного шаттла выглядит странно.

**Детальное описание как повторить возникновение проблемы**:
Вызвать блоб, посмотреть, прилетит ли эвакуационный/трансфер

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Не нашел "epidemic" в коде нигде кроме этого места.

**Comment by Injazz** [comment]
Это моя вина, я щитоспавнул шаттл, думал что он не работает. А это игра ему не дала прилететь. МДА

**Comment by Zurro13** [comment]
Я, собственно, поднимал вопрос не о спавне шаттла вообще, а о разнице кода для трансфера и эвакуации. Просто проверить сегодня не могу, тазик, за которым я сейчас работаю, сервер и клиент одновременно не тянет.

**Comment by NazarFogmann** [comment]
Смотри, шаттл прилетает, НО ОН НЕ УЛЕТАЕТ, много раз такое видел

**Comment by sswwyyaatt** [comment]
Прост ему лампово, вот и не улетает
4 июня 2016 г. 4:08 ПП пользователь "NazarFogmann" <notifications@github.com>
написал:

**Comment by Injazz** [comment]
@NazarFogmann распиши поподробней и в отдельной теме

**Comment by NazarFogmann** [comment]
> распиши
Нечего расписывать, с ЦК приходит сообщение, мол так и так у вас там пиздец, устраните проблему и повторите позднее
