### ISSUE TITLE
Бухло и "я"

### ISSUE THREAD

**Issue by Templariumer** [ITBlackwood/ATMTA-Paradise#49]
**Описание проблемы**:
Буква "я" отображается некорректно, когда персонаж(предположительно только vulpkanin, надо проверить остальных) пьян.

**Что должно было произойти**: 
slurs, "Раздева'йся;"

**Что произошло вместо этого**:
slurs, "Раздева'йс'&#2'55;"

**Почему это плохо/Какие последствия этого:**
Режет глаз и вообще не должно так работать.

**Детальное описание как повторить возникновение проблемы**:

1. Допиваешься до состояния, когда в слова начинают подставляться " ' "
2. Блюешь и строчишь на гитхаб

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Только то, что это был vulpkanin, а не человек. На людях не проверял.

**Comment by ITBlackwood** [comment]
При опьянении апостроф ставится рандомно в любое место предложения. Буква "я" заменяется санитайзами в коде на &#255; Который и преображается в чате как "я". Поэтому при опьянении апостроф может рандомно затесаться среди &#255; и вызвать то что ты привел в примере. Как такое фиксить? Да никак, только опьянение убрать можно.
