### ISSUE TITLE
Консоль у экспериментора не хочет обновляться с сервером

### ISSUE THREAD

**Issue by NazarFogmann** [ITBlackwood/ATMTA-Paradise#50]
**Описание проблемы**:
Консоль у экспериментора не хочет обновляться с сервером

**Что должно было произойти**: 
Консоль обновиться с сервером

**Что произошло вместо этого**:
Консоль не обновляется

**Почему это плохо/Какие последствия этого:**
Очень, ведь эксперименты негде ставить

**Детальное описание как повторить возникновение проблемы**:
подходишь-обновляешь-ничего не происходит

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Никаких

**Comment by ITBlackwood** [comment]
Надо синхронизировать экспериментор с консолью **не в самой консоли**, а **непосредственно в эксперименторе.**
