### ISSUE TITLE
Магия суицида через cable resistants.

### ISSUE THREAD

**Issue by Templariumer** [ITBlackwood/ATMTA-Paradise#51]
**Описание проблемы**:
suicide работает со связанными руками.

**Что должно было произойти**: 
ну, должен был хотя бы язык заглотить

**Что произошло вместо этого**:
Свернул шею со связанными руками.

**Почему это плохо/Какие последствия этого:**
Не уверен, что стоит вообще разрешать суицид со связанными руками.

**Детальное описание как повторить возникновение проблемы**:
1)связать руки
2)написать suicide

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Обычный человек, обычные cable resistants
В наручниках не проверял.

**Comment by ITBlackwood** [comment]
Ну я думаю что в реальной жизни можно и голову свернуть, и язык откусить, и глаза выдавить со связанными руками. Опять же, нет уточнения насчет того ГДЕ находились руки. Так что да, это смутная проблема. Ее можно решать, а можно и оставить.
