### ISSUE TITLE
У packet of coffee arabica seeds отсутствует спрайт.

### ISSUE THREAD

**Issue by Templariumer** [ITBlackwood/ATMTA-Paradise#52]
Вместо пачки нарисован Красный кружок с красным вопросиком.

**Comment by Templariumer** [comment]
Спрайты присутствуют в Seeds_OLD, что странно. Может быть, кофе ВООБЩЕ НЕ ДОЛЖНО БЫТЬ? (Драматически уходит...)
![default](https://cloud.githubusercontent.com/assets/19695315/15855382/61d8e5ba-2cd9-11e6-8e13-450fabbe1b91.PNG)

**Comment by ITBlackwood** [comment]
Скорее всего. Вообще кстати не видел чтобы кофе выращивали.
