### ISSUE TITLE
diona nymph не станится от турелей(Баг или фича?)

### ISSUE THREAD

**Issue by Templariumer** [ITBlackwood/ATMTA-Paradise#53]
**Описание проблемы**:
diona nymph не может словить стан от туррели
**Что должно было произойти**: 
Диона должна впасть в стан

**Что произошло вместо этого**:
проджектайлы не приносят никакого успеха.

**Почему это плохо/Какие последствия этого:**
Не очень плохо, просто либо так задумано, либо туррели не должны стрелять в диону, либо она должна станиться

**Детальное описание как повторить возникновение проблемы**:
Это очень важно. Опишите действия, которые, по вашему мнению, привели к багу.
1)Быть diona nymph
2)Забраться в аплоад ИИ, например.

**Comment by ITBlackwood** [comment]
Турели вообще реагируют на любого моба в аплоуде, вне зависимости от его типа.

**Comment by Templariumer** [comment]
Не совсем, они не агрятся на глав, например.

**Comment by ITBlackwood** [comment]
Ну у дион и, например, simple_animal доступа нет. Поэтому и агрятся. Вопрос закрыт
