### ISSUE TITLE
ВЕРНИТЕ ИЛЬЮ 

### ISSUE THREAD

**Issue by sswwyyaatt** [ITBlackwood/ATMTA-Paradise#54]
**Описание проблемы**:
В чем суть проблемы?
ИЛЬЯ УШЕЛ ВЕРНИТЕ ЕГО
**Что должно было произойти**: 
ОН ДОЛЖЕН АДМИНИТЬ СС13

**Что произошло вместо этого**:
ОН УШЕЛ, ЭТО ПОЛНЫЙ ПИЗДЕЦ БЛЯДЬ

**Почему это плохо/Какие последствия этого:**
ПИЗДЕЦ КАК СЕРОООООЗНО ВСЁ

**Детальное описание как повторить возникновение проблемы**:
Это очень важно. Опишите действия, которые, по вашему мнению, привели к багу.
У НЕГО БОМБАНУЛО ПОХОДУ ( НЕ МОГУ В КОД )

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Все, что может нам помочь.
Я МОГУ ПОМОЧЬ ЛАЙКАМИ

**Comment by BatyaMedic** [comment]
бля че за хуйня

**Comment by BatyaMedic** [comment]
нахуй пошел

**Comment by NazarFogmann** [comment]
бля че за хуйня

**Comment by ITBlackwood** [comment]
По вашей просьбе, Илью вернули. Спасибо за беспокойство

**Comment by Signmark** [comment]
Я здесь во плоти
