### ISSUE TITLE
Injazz - дебил

### ISSUE THREAD

**Issue by Signmark** [ITBlackwood/ATMTA-Paradise#55]
**Описание проблемы**:
Дебил Injazz погорел и удалил свой гитхаб, теперь у него нету доступа к репозиторию

**Что должно было произойти**: 
Injazz не должен быть дебилом и должен иметь доступ к репозиторию

**Что произошло вместо этого**:
Он дебил и не имеет доступа.

**Почему это плохо/Какие последствия этого:**
Дебилы это плохо. Отсутствие доступа это оч плохо. 
Главный кодер - дебил без доступа - ЭТО УЖАСНО.

**Детальное описание как повторить возникновение проблемы**:
1)Будьте Injazz'ом.
2)Воспламените свою жеппу
3)Удалите гитхаб
4)cry a lot
5)Рычите, порыкивайте, урчите: покажите всем своим видом, что вы - ДЕБИЛ.

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Будет классно если Injazz дадут целительных пиздов и еще проведут доступ на его второй акк.
Это его второй акк, пруфы могу предоставить в аську джаббер одноклассники, по особой просьбе могу скинуть и в вк

**Comment by BatyaMedic** [comment]
да вы заебали
