### ISSUE TITLE
Портировать Goonlight

### ISSUE THREAD

**Issue by Signmark** [ITBlackwood/ATMTA-Paradise#56]
/vg/station заимели систему освещения с гунов.
Неизвестно, когда парадайзы решатся на портирование, поэтому портируем сами.
https://github.com/d3athrow/vgstation13/pull/10064/files - здесь весь код, ясное дело, что если вы его просто вставите, он работать не будет.

Превью освещения-
![image](https://cloud.githubusercontent.com/assets/19763675/15816432/33e46f5a-2bec-11e6-8d43-43c790461f7d.png)

**Comment by NazarFogmann** [comment]
пощади парней, у них и так лагов хватает

**Comment by ITBlackwood** [comment]
Освещение не вызывает лагов, алло.

**Comment by Signmark** [comment]
@NazarFogmann веге летает, настроим тиклаг у нас и освещение будет работать не вызывая лагов.

**Comment by ITBlackwood** [comment]
0,1 ticklag, 0 tickcomp 
МММ ЛЕТАТЬ ТО БУДЕМ

**Comment by Signmark** [comment]
@ITblackwood 
А че на вг такой текла и стоит

**Comment by ITBlackwood** [comment]
@Signmark 
Да кому нужна вообще такая super sanic speed

**Comment by Signmark** [comment]
@ITBlackwood глянь как четко на вг
