### ISSUE TITLE
runtime error: null.timeofdeath

### ISSUE THREAD

**Issue by ITBlackwood** [ITBlackwood/ATMTA-Paradise#58]
**Описание проблемы**:
Рантаймы null.timeofdeath;  observer.dm 155 строка

**Что должно было произойти**: 
Вообще такого не должно быть, рантаймы вообще штука не самая хорошая.

**Что произошло вместо этого**:
Произошли рантаймы

**Почему это плохо/Какие последствия этого:**
Не знаю, но лучше убрать это. 

**Детальное описание как повторить возникновение проблемы**:
Запустить сервер, и смотреть по логам. Очевидно что должен быть обсервер

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Никаких особенностей.

**Comment by Signmark** [comment]
полную ошибку плз

**Comment by BatyaMedic** [comment]
уберите бьонд лучше

**Comment by Signmark** [comment]
![image](https://cloud.githubusercontent.com/assets/19763675/15829856/0839892e-2c2f-11e6-90c4-3cd1f49d64ee.png)
Видишь, в чем дело? Я не вижу, потому что инфы мало

**Comment by ITBlackwood** [comment]
В логах не нашел, подробнее кинуть не могу.

**Comment by Signmark** [comment]
@ITBlackwood игра крашится от этого?

**Comment by ITBlackwood** [comment]
Нет, но возможно очень сильно зависает.

**Comment by ITBlackwood** [comment]
Ошибка вроде больше не давала о себе знать. Клоз.
