### ISSUE TITLE
Интерфейс вендоматов не обновляется.

### ISSUE THREAD

**Issue by ITBlackwood** [ITBlackwood/ATMTA-Paradise#63]
**Описание проблемы**:
Интерфейс вендоматов не обновляется до тех пор пока не закрыть окно с интерфейсом, и снова не кликнуть по вендомату. 

**Что должно было произойти**: 
Интерфейс должен обновляться при нажатии кнопок

**Что произошло вместо этого**:
Бесконечная загрузка.

**Почему это плохо/Какие последствия этого:**
Не серьезный баг, но жутко неудобный. Лучше исправить побыстрее.

**Детальное описание как повторить возникновение проблемы**:
Я даже не уверен что такое у всех случается. Было 2-3 случая, включая мой.

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
От режима и роли не зависит. Конфиги сервера тоже вроде не влияют.

**Comment by Zurro13** [comment]
Что примечательно, у меня эта проблема возникала с автоматами с едой (Getmore Chocolate и Chang), с напитками не проверял, и ни разу не возникала с сигаретным, ХЗ почему.

**Comment by NazarFogmann** [comment]
У меня со всеми автоматами такая хуйня, надо отойти на 1 тайл, подождать пока интерфейс появится, и подойти снова

**Comment by Signmark** [comment]
fixed

**Comment by ITBlackwood** [comment]
как пофиксил кстати?
