### ISSUE TITLE
РД и нелогичный доступ в медбэй

### ISSUE THREAD

**Issue by ITBlackwood** [ITBlackwood/ATMTA-Paradise#67]
**Описание проблемы**:
У РД нет прямого доступа в медбэй через двери в приемной

**Что должно было произойти**: 
Доступ должен быть.

**Что произошло вместо этого**:
Доступа нет.

**Почему это плохо/Какие последствия этого:**
Потому что это не логично поскольку через морг или генетическую лабораторию у РД есть доступ в медбэй. Бежать и делать крюк - это пиздец.

**Детальное описание как повторить возникновение проблемы**:
Просто возьмите РД и попробуйте войти в медбэй через приемную.

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Да в общем-то все.

**Comment by Signmark** [comment]
Ну давай еще тогда СЕ дадим доступ в медбей или СМО дадим доступ в РД.

Очевидно, что доступ в морг и генетику обусловлен спецификой работы. А нахуя ему доступ через приемную? Все равно он торчит в своем отделе, а оттуда проще пройти через генетику в медбей. Хуйня какая-то

**Comment by ITBlackwood** [comment]
РД может бывать в медбэе гораздо чаще чем ему нужно. Замена оборудования, снабжение новыми инструментами, операции на глазных имплантах, и.т.д.
Я просто клоню к тому что доступ в медбэй через приемную тоже будет удобен.

**Comment by Signmark** [comment]
@ITBlackwood БЮРОКРАТИЯ БЛЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯДЬ

**Comment by ITBlackwood** [comment]
U fucker.
