### ISSUE TITLE
Уберите соляры со спутника

### ISSUE THREAD

**Issue by NazarFogmann** [ITBlackwood/ATMTA-Paradise#76]
Уберите соляры с инженерного спутника, чтобы их самому надо было собирать. Сделайте со спутника выход в космос, ибо выход со спутника один- Массдрайвер

**Comment by Zurro13** [comment]
Отгоняешь шаттл на станцию, и вот тебе выход. Дополнительные соляры надо собирать в любом случае, если ты собираешься достраивать недостроенную станцию, а иначе что ты там вообще делал на инженерном аутпосте? Построй сам шлюз, в конце концов, ты инженер или где?
Ну еще пожалуйся на то. что релей там уже есть, и его не надо из частей собирать.

**Comment by ITBlackwood** [comment]
На инж. спутнике располагаются телекоммы, которые этими солярами и питаются, поэтому убирать их никак нельзя.

**Comment by NazarFogmann** [comment]
Я не говорю что их просто надо оттуда убрать, в чем проблема поставить  коробку с частями?

**Comment by ITBlackwood** [comment]
В том что они должны быть настроены с начала раунда для того чтобы работал телекомм.
Что-то я сильно сомневаюсь что после синги инженеры побегут настраивать соляры на спутнике

**Comment by Zurro13** [comment]
Там не все телекоммы. Более того. передатчик. который там, еще и отключен в начале раунда, если я не ошибаюсь.
Тем не менее я не вижу смысла их оттуда убирать. Это противоречит логике построения карт, на которых. как правило, станция и все аутпосты построены и готовы к эксплуатации. нужно только (привинтить к полу и подключить ускоритель частиц/подключить к общей сети солнечные батареи/подать газ в ТЭГ/инициировать разрушение ядра СМ). В этом случае отсутствие работоспособного источника питания. который надо только подключить, будет смотреться очень странно.
Тем более, что пост запакован и подготовлен к строительству станции, которая там рядом висит. Если настолько нечем заняться - всегда можно заказать соляры в карго и собирать их уже на недостроенной станции. которую надо тоже запитать. Там работы по восстановлению - убиться можно всей инженерной смене (я в свое время осилил этот подвиг дроном за 6 часов смены, было очень нечего делать).
