### ISSUE TITLE
Мапа для хайрп

### ISSUE THREAD

**Issue by NazarFogmann** [ITBlackwood/ATMTA-Paradise#77]
https://yadi.sk/d/YyB4vT5FsSXc2
тутачки кибериад
![hrp_area](https://cloud.githubusercontent.com/assets/19737119/15993849/91114dd8-30fb-11e6-8b3a-1fd8ead3221e.png)
![hrp_](https://cloud.githubusercontent.com/assets/19737119/15993850/91191ce8-30fb-11e6-9d1e-a28a16e37909.png)

**Comment by ITBlackwood** [comment]
Создай отдельный бранч и залей как ПР, толку нам от того что ты Яндекс.диск используешь?

**Comment by ITBlackwood** [comment]
и Зону Security лучше убрать, и вернуть как было. А то получится путаница с АПЦ и распределением энергии.

**Comment by NazarFogmann** [comment]
> и Зону Security лучше убрать
Зоны не нарушены
![image](https://cloud.githubusercontent.com/assets/19737119/16001745/8f86ca54-315c-11e6-8281-d88c61a75dbc.png)

**Comment by NazarFogmann** [comment]
И да, пойду реквест сделаю

**Comment by ITBlackwood** [comment]
Окей, так лучше
