### ISSUE TITLE
Какое-то дерево translated все лейблы

### ISSUE THREAD

**Issue by Signmark** [ITBlackwood/ATMTA-Paradise#79]
**Описание проблемы**:
Labels оказались русскими

**Что должно было произойти**: 
Лейбы was илитные english

**Что произошло вместо этого**:
Labels now руснявая shit для быдла

**Почему это плохо/Какие последствия этого:**
Теряется elite нашего repository

**Детальное описание как повторить возникновение проблемы**:
Будьте black wood, go to лейблы, переведите Labels на лейблы, sacrifice курицy во славу Satan.

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Pls im elite программист изза русских букв у меня компиляция в голове broken

**Comment by NazarFogmann** [comment]
Hahahha какой nice joкес

**Comment by ITBlackwood** [comment]
Чего блядб? Приведи проблему нормально

**Comment by Signmark** [comment]
@ITBlackwood лох в мемах не шаришь
