### ISSUE TITLE
Звук Deal-Up модема для киборгов

### ISSUE THREAD

**Issue by OddyBeholdie** [ITBlackwood/ATMTA-Paradise#83]
Shervin walrus/(Cyber-Killer) (?) (PP) (VV) (SM) (FLW) (CA) (REJT) : А у боргов когда-нибудь появится кнопочка, чтобы издавать звук как диал-ап? 

Мне нравится эта идея и даже в ЭрПэ её можно использовать.

**Comment by ITBlackwood** [comment]
А что, забавно. Прям щас запилю.

**Comment by ITBlackwood** [comment]
Фича добавлена. Клоз.
