### ISSUE TITLE
Гуносвет не работает в гейтвей миссиях

### ISSUE THREAD

**Issue by NazarFogmann** [ITBlackwood/ATMTA-Paradise#84]
**Описание проблемы**:
В гейтвее нихуя не видно дальше 1 тайла, и вообще источники света не работают

**Что должно было произойти**: 
Свет должен СВЕТИТЬ наверное

**Что произошло вместо этого**:
Я вижу вокруг на 1 тайл

**Почему это плохо/Какие последствия этого:**
Нихуя не видно, и меня отпиздолил синдикот

**Детальное описание как повторить возникновение проблемы**:
Идешь в гейтвей>наблюдаешь жепу

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
У вас вгсвет видно, в курсе?

**Comment by ITBlackwood** [comment]
Во-первых гунлайт*
Во-вторых, ну, ПОДРОБНЕЕ ПЛЗ, СКРИНЫ ТАМ, ВСЕ ТАКОЕ.

**Comment by NazarFogmann** [comment]
![image](https://cloud.githubusercontent.com/assets/19737119/16132173/b71fc5fa-341a-11e6-83f7-22f4746c12ac.png)
Это русский отель, там светло должно быть

**Comment by NazarFogmann** [comment]
+ свет с пда

**Comment by ITBlackwood** [comment]
Ну видимо нет обработки на определенных z-уровнях, а именно, в эвэй-миссиях.

**Comment by Signmark** [comment]
Я тоже это заметил
НУ БЛЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯТЬ

**Comment by Signmark** [comment]
Изи, фикс будет через 20 минут

**Comment by Signmark** [comment]
Гуносвет - причина долгих перезапусков. Гуносвета больше нет.
