### ISSUE TITLE
Пластырные вопли

### ISSUE THREAD

**Issue by ITBlackwood** [ITBlackwood/ATMTA-Paradise#85]
**Описание проблемы**:
При использовании пластыря персонаж орет, словно ему конечность отрезают

**Что должно было произойти**: 
Персонаж должен слегка издать что-нибудь вроде "Аааай" и завалить хлебало.

**Что произошло вместо этого**:
В мошонку персонажа ржавой киркой долбится сам сатана, вызывая боль соизмеримую с десятью беременностями одновременно. 

**Почему это плохо/Какие последствия этого:**
Сульфазипрлдрпшугзфргшцин вызывает жжение, но никак не обливает кожу лавой.

**Детальное описание как повторить возникновение проблемы**:
Возьмите любой пластырь, используйте его, наслаждайтесь воплями.

**Как проблему решить?**:
Добавить другой звук для таких пластырей, вот и все.

**Comment by ITBlackwood** [comment]
Я оставил себе это как пометку. Завтра поставлю новый звук.

**Comment by NazarFogmann** [comment]
Ballon Gear Kosmonavtiki V: The Phantom Scream

**Comment by ITBlackwood** [comment]
Изменил звуки.
