### ISSUE TITLE
FOKKEN HELL MATE

### ISSUE THREAD

**Issue by ITBlackwood** [ITBlackwood/ATMTA-Paradise#89]
**Описание проблемы**:
В чем суть проблемы?
РЕФАКТОРЫ.

![08c117f4a0b9f1d3fd49e935d338f54f](https://cloud.githubusercontent.com/assets/12843420/16179429/5037e7c0-3698-11e6-983d-498adbd6bb8b.jpg)

**Почему это плохо/Какие последствия этого:**
Насколько важна эта проблема?

Перезаливать эмоуты!

**Детальное описание как повторить возникновение проблемы**:
Я НИЧЕ НЕ ДЕЛАЛ ЭТО ВСЕ ОНИ.
**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Напомните, какие мы вообще эмоуты добавляли?

**Comment by Signmark** [comment]
*dialup
ayy lmao

**Comment by NazarFogmann** [comment]
Мое увожение

**Comment by ITBlackwood** [comment]
@NazarFogmann Нет, его мы не добавляли, и вообще это был бы не эмоут даже.

**Comment by Signmark** [comment]
@ITBlackwood Сделай кстати такое к Tip Fedora

**Comment by Signmark** [comment]
емоут система отменена
