### ISSUE TITLE
У вас графика протекает.

### ISSUE THREAD

**Issue by Dreyze** [ITBlackwood/ATMTA-Paradise#90]
**Описание проблемы**:
В чем суть проблемы?
●При использовании "stretch to fit" графика становится размытой/нечёткой.

**Что должно было произойти**: 
Что должно произойти? Это важно, чтобы понять, баг ли это вообще.
 ●Произойти должна была нормальная графика.

**Что произошло вместо этого**:
Что произошло и насколько это отличается от того, что вы ожидали?
 ●**НЕ** нормальная графика.

**Почему это плохо/Какие последствия этого:**
Насколько важна эта проблема?
 ●Очень важна.

**Детальное описание как повторить возникновение проблемы**:
Это очень важно. Опишите действия, которые, по вашему мнению, привели к багу.
 ●DirectX 11.1 и кривые руки разработчиков VG билда.

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Все, что может нам помочь.
●При использовании увеличения 1.5; 2; 3 (48x48; 64x64; 96x96) а также уменьшения (32х32) картинка становится чёткой. Но играть на этих значениях трудно. По сути можно "вписать" что-то по типу 1.1

![1](https://cloud.githubusercontent.com/assets/20068754/16233399/45c48f1c-37df-11e6-80e4-40494a0ad23d.jpg)

![2](https://cloud.githubusercontent.com/assets/20068754/16233427/5ba07292-37df-11e6-87ac-e98c6b6fa326.jpg)

Версия BYOND самая последняя. 510.1347

**Comment by NazarFogmann** [comment]
Распиши свою ось, разрешение и тому подобное, тут не экстрасенсы сидят 
(и да у нас тут не  /vg/ билд)

**Comment by NazarFogmann** [comment]
И версию бйонда напиши, на всякий

**Comment by NazarFogmann** [comment]
Не вижу разрешения

**Comment by Dreyze** [comment]
Режим экрана, мой внимательный кодер.

**Comment by NazarFogmann** [comment]
> Режим экрана, мой внимательный кодер.

Покрути разрешение, в нем корень проблемы

**Comment by Dreyze** [comment]
> Покрути разрешение, в нем корень проблемы
Нет, не в нём. Проверил для чистоты эксперимента. Одно и то же. Кстати, пробовал подключать монитор, но воз и ныне там. 
Ошибка на уровне драйверов, совместимости и кода.

**Comment by Dreyze** [comment]
> ●При использовании увеличения 1.5; 2; 3 (48x48; 64x64; 96x96) а также уменьшения (32х32) картинка становится чёткой. Но играть на этих значениях трудно. По сути можно "вписать" что-то по типу 1.1.
Говорю же.

**Comment by NazarFogmann** [comment]
У всех поцанов нормально, проблема в тебе, и да после квоты пропускай строку

**Comment by NazarFogmann** [comment]
Аа бля
Попробуй вот что, выстави стретч ту фит, и перезапусти окно с игрой

**Comment by Dreyze** [comment]
> Попробуй вот что, выстави стретч ту фит, и перезапусти окно с игрой.

Что???

**Comment by NazarFogmann** [comment]
Смотри
Зайди в игру,выстави стретч ту фит
закрой дримсикер
Снова зайди в игру

У меня такая хуйня переодически всплывала на анусах

**Comment by Dreyze** [comment]
Мне просто сейчас проклацать по красному крестику? ))

**Comment by NazarFogmann** [comment]
Да

**Comment by NazarFogmann** [comment]
(я тебя уже забил боллоном)

**Comment by Dreyze** [comment]
А графику завезли?

**Comment by Signmark** [comment]
@Dreyze Stretch to Fit - это ты просто развернул окно, это функция в директиксе/виндовсе или фича бьонда? Как мне повторить это.

**Comment by Signmark** [comment]
Если ты нажал кнопку автонастройки на мониторе, то лол, это проблема монитора
