### ISSUE TITLE
Гунокасса.

### ISSUE THREAD

**Issue by ITBlackwood** [ITBlackwood/ATMTA-Paradise#93]
Нечего описывать. Просто ремайндер чтобы я портировал кассу с гунов.

**Comment by Signmark** [comment]
ЭКОНОМИКА

**Comment by Signmark** [comment]
https://github.com/d3athrow/vgstation13/issues/3856
Глянь это

**Comment by ITBlackwood** [comment]
Чтоб я еще раз полез портировать то что у нас уже есть в билде....
